#!/bin/bash
#
# Prakhar Saxena
#
# 2018-06-07
#


./assn4 init 15 = 10 1 0 0
#It shouldn't print anything out, but it'll create a file called 'temp'
cat temp

./assn4 purchase 38 = 0 0 0 2
#it should return change 2 0 0 0
cat temp

./assn4 change 0 1 = 5
# it should return the change that you asked for
# expected output: 5 0 0 0 
cat temp

./assn4 report
#it should should basically have the same output as cat temp

if [ $? -eq 0 ]; then
	echo "success?"
fi

./assn4 purchase 8 = 7 0 0 0
#should throw an error

./assn4 init 12 = 1 4 2 3 4 4 2
#should throw a bad argument error

