######  Python  ###########
# if you did this in Python, single file, accounts

.PHONY : build view clean

build :
	@# "Not much to do here.  I did this in Python"
	chmod +x accounts

view :
	@\less accounts

clean :
	@\rm *.pyc

