all: program1 program2 program3 program4 program5

program1: program1.c
 gcc -o program1 program1.c

program2: program2.c
 gcc -o program2 program2.c

program3: program3.c
 gcc -o program3 program3.c

program4: program4.c
 gcc -o program4 program4.c

program5: program5.c
 gcc -o program5 program5.c