main: rushhour.py
	python rushhour.py print "  o aa|  o   |xxo   |ppp  q|     q|     q"

print: rushhour.py
	python rushhour.py print

done: rushhour.py
	python rushhour.py done

next: rushhour.py
	python rushhour.py next

test: rushhour.py
	python rushhour.py test

random: rushhour.py
	python rushhour.py random "      |      |      |      |      |      "

bfs: rushhour.py
	python rushhour.py bfs "  o aa|  o   |xxo   |      |      |      "
